#!/bin/bash

# My shell scripts evironment variable. It's important.
export MYSHELLDIR=$HOME/myshell
if [ ! -d $MYSHELLDIR ]; then
    echo -e "\\033[31m$MYSHELLDIR 目录不存在，操作失败\\033[0m"
    return 0
fi

# Source all of the sh files under the path $param1. It's not recursive.
# param1: specify the file path to execute source.
function my_source()
{
    if [ -z "$1" ]; then
        echo -e "\\033[31m参数错误！［Function:my_source of source file.］\\033[0m"
        return 0
    fi
    for file in `ls $1`; do
        source "$1/$file"
    done
}

LOCALIZATION_ENABLED=true
# Config the supporting of localization
function gettxt() {
    if $LOCALIZATION_ENABLED; then
        gettext -s "$@"
    else
        echo "$@"
    fi
}

# source the files in MYSHELLDIR/utils/
my_source $MYSHELLDIR/utils

# Source the files in MYSHELLDIR/bash_completion.d/
# For enable the args auto completion when I input my own commands.
my_source $MYSHELLDIR/bash_completion.d

# alias check returned error number from function.
alias chk_return='if (( 0 != $? )); then return 1; fi'

# Commands.
MYCOMMANDDIR=$MYSHELLDIR/commands
alias c='source $MYCOMMANDDIR/cd $*'
alias g='source $MYCOMMANDDIR/grep $*'
alias f='source $MYCOMMANDDIR/find $*'
alias v='source $MYCOMMANDDIR/vim $*'
# costomize command 'nautilus'
alias n='source $MYCOMMANDDIR/nautilus $*'
alias share='source $MYCOMMANDDIR/share'
alias add-phone='source $MYCOMMANDDIR/add-phone'
alias switch-git='source $MYCOMMANDDIR/switch-git'
alias switch-locale='source $MYCOMMANDDIR/switch-locale'
alias add-f='source $MYCOMMANDDIR/add-f'
alias rm-f='source $MYCOMMANDDIR/rm-f'

# kt
#MYKTSH=$MYSHELLDIR/kt
#source $MYKTSH/repo
#alias put='source $MYKTSH/put $*'
#alias get='source $MYKTSH/get $*'
#alias merge='source $MYKTSH/merge $*'
#alias kt='source $MYKTSH/kt $*'
#alias rm-='source $MYKTSH/rm $*'
#alias mm-='source $MYKTSH/mm $*'

# ftp servers:
alias 99='nautilus ftp://10.10.100.99/liubzh'
#alias 100='nautilus ftp://10.10.100.100/liubzh'
alias 100='nautilus ftp://10.10.100.100'
alias 90='source $MYKTSH/90 $*'

# Other
alias cq='clearquest &'
alias vnccfg='vncconfig &'

# python
VIR_ENV_SH="/usr/local/bin/virtualenvwrapper.sh"
if [ -f $VIR_ENV_SH ]; then
    source $VIR_ENV_SH
fi

# java
# 如果想对所有用户进行配置
# 可以考虑写进 /etc/profile文件
JAVA_HOME="$HOME/Development/java/jdk"
JRE_HOME="$JAVA_HOME/jre"
if [ -d "$JAVA_HOME" ]; then
    export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib:$CLASSPATH
    export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH
fi

# eclipse for python
ECLIPSE="$HOME/Development/python/eclipse/eclipse"
if [ -f $ECLIPSE ]; then
    alias eclipse='$MY_ECLIPSE'
fi

# Android Studio
ANDROID_SDK_HOME="$HOME/Development/android/sdk"
export PATH=$ANDROID_SDK_HOME/platform-tools:$ANDROID_SDK_HOME/tools:$PATH
ANDROID_STUDIO="$HOME/Development/android/android-studio/bin/studio.sh"
if [ -f $ANDROID_STUDIO ]; then
    alias android-studio=$ANDROID_STUDIO
fi

# wechat
WECHAT="$HOME/Applications/electronic-wechat/electronic-wechat"
if [ -f $WECHAT ]; then
    alias wechat="$WECHAT"
fi
