#!/bin/bash

# Example:
function _foo() {
    my_opt="-h --help -f --file -o --output"
    local cur prev opts

    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="${my_opt}"

    if [[ ${cur} == -* ]] ; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi

    return 0 # return.
    case "${prev}" in
        -h|--help)
            ;;
    esac

}
#complete -o default -F _foo foo
