#!/bin/bash

######## Script Information. BGN ########
# Author: liubingzhao.
# Date: 2016-12-27
# Relative Command: commands/adb
######## Script Information. END ########

function _adb() {
    local my_opt="push pull sync shell emu logcat forward reverse jdwp install install-multiple uninstall bugreport restore disable-verity enable-verity keygen help version wait-for start-server kill-server get-state get-serialno get-devpath remount reboot sideload root unroot usb tcpip ppp reconnect"
    local v_opts="brief color long printable process raw tag thread threadtime time usec"
    local logcat_opts="-s -r -n -v -D -c -t -T -g -L -b -B -S -G -p -P"
    local cur prev opts

    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    prev2="${COMP_WORDS[COMP_CWORD-2]}"
    opts=""

    if [[ ${prev} == adb ]] ; then
        opts=${my_opt}
    elif [[ ${prev} == -v && ${prev2} == logcat ]]; then
        opts=${v_opts}
    elif [[ ${prev} == logcat && ${cur} == -* ]]; then
        opts=${logcat_opts}
    fi
    if [[ ${prev2} == push ]]; then
        # If command is "adb push", and argument is like *out*/system/*,
        # autocut and complete the next argument.
        if [ -n "${prev}" ]; then
            if [[ ${prev} == *out*/system/* ]]; then
                opts=system/${prev#*/system/}
            fi
        fi
    fi
    if [ -n "${opts}" ]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    fi
    return 0
}

complete -o default -F _adb adb
