#!/bin/bash

######## Script Information. BGN ########
# Author: liubingzhao.
# Date: 2016-12-27
# Relative Command: commands/grep
######## Script Information. END ########

function _g() {
    # Arguments start with '-'
    local my_opt_short="-C2 -c -h"
    # Arguments start with '--'
    local my_opt_long="--context=2 --count --exclude --exclude-dir --help --include --noi"
    local my_log_file="crash_log kernel_log events_log main_log radio_log radio_log"
    local my_file_type=".{aidl,c,cpp,java,log,mk,sh,txt,xml,zip} strings.xml AndroidManifest.xml config.xml styles.xml themes.xml ${my_log_file}"

    COMPREPLY=()

    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"
    local opts=

    # Arguments start with '--' and '-'
    if [[ ${cur} == --* ]] ; then
        opts=${my_opt_long}
    elif [[ ${cur} == -* ]]; then
        opts=${my_opt_short}
    fi

    if [[ $prev == --include || $prev == --exclude ]]; then
        opts=${my_file_type}
    fi

    if [ -n "${opts}" ]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    fi
    return 0
}
complete -o default -F _g g
