#!/bin/bash
# Written by liubzh

########## merge ##########
function _merge() {
    my_opt="-p --patch -c --commit -b --branch -h --help"
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="${my_opt}"
    if [[ ${cur} == -* ]] ; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi
}
complete -o default -F _merge merge
