#!/bin/bash
# Written by liubingzhao.

function _TmakeGionee() {
    local my_args_short="-l -h -t -q -j -m -n -r -u -c -C -a -s -i -p"
    local my_args_long="--new --remake --update_api --copy_target --copy_gionee --android --all --sign --setup_ccache --image --project"
    local my_modules="bootimage systemimage userdataimage update-api kernel otapackage modem"
    local my_projects="G1605A G1602A"
    local cur prev opts

    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=""

    if [[ ${cur} == --* ]]; then
        opts="${my_args_long}"
    elif [[ ${cur} == -* ]]; then
        opts="${my_args_short}"
    elif [[ ${cur} == G* || ${cur} == B* ]]; then
        opts="${my_projects}"
    elif [[ ${prev} == *TmakeGionee ]] ; then
        opts="${MY_GN_PROD}"
    elif [[ ${prev} == -i || ${prev} == --image ]] ; then
        opts="${my_modules}"
    fi
    if [ -n "${opts}" ]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    fi
    return 0
}
complete -o default -F _TmakeGionee TmakeGionee
