#!/bin/bash

######## Script Information. BGN ########
# Author: liubingzhao.
# Date: 2016-12-23
######## Script Information. END ########

# All the global variables in this script.
function init_global_variables() {
    PRE_TEXTDOMAINDIR=$TEXTDOMAINDIR
    PRE_TEXTDOMAIN=$TEXTDOMAIN
}

function print_help() {
    cat << Help
$(gettxt "m | Binzo's customized TmakeGionee command.")
$(gettxt 'Usage:') m [PACKAGE]
Help
}

# Parse and validate the arguments.
# return 0: ok
# return 1: invalid or print help.
function parse_and_check_args () {
    while [ $# -gt 0 ];do
        case "$1" in
        -h|--help|\?)
            print_help
            return 1    # exit.
            ;;
        *)
            shift
            ;;
        esac
    done
}

# Internationalization and localization
# Set local language support. only for zh_CN.
# Reference directory: /usr/local/share/locale
function set_localization() {
    export TEXTDOMAINDIR="${MYSHELLDIR}/lang/locale"
    export TEXTDOMAIN="m"
}

function unset_localization() {
    if [ -z "$PRE_TEXTDOMAINDIR" ]; then
        unset TEXTDOMAINDIR
    fi
    if [ -z "$PRE_TEXTDOMAIN" ]; then
        unset TEXTDOMAIN
    fi
}

function main() {
    init_global_variables

    # Check arguments.
    parse_and_check_args "$@"
    case "$?" in
    1)
        return 1
        ;;
    *)
        ;;
    esac

    if [ -z "${MY_GN_PROJ}" ]; then
        echo "MY_GN_PROJ is null, please execute 'switch-proj' to set it."
        return 1
    fi
    local my_cmd=
    if [ -f Android.mk ]; then
        # If Android.mk exists in current directory
        local mk_dir=`pwd`
        c r
        local root_dir=`pwd`
        mk_dir=${mk_dir#*$root_dir/}
        my_cmd="./TmakeGionee -t ${MY_GN_PROJ} -p ${mk_dir}"
    elif [ -f TmakeGionee ]; then
        # If currently in the android project root directory.
        if [ -z "$1" ]; then
            my_cmd="./TmakeGionee -t ${MY_GN_PROJ} -n"
        elif [ ! -d $1 ]; then
            echo "No such directory."
            return 1
        elif [ -f $1/Android.mk ]; then
            my_cmd="./TmakeGionee -t ${MY_GN_PROJ} -p $1"
        fi
    fi
    if [ -n "${my_cmd}" ]; then
        echoW ${my_cmd}
        read -p "Press <Enter> to execute this command: "
        ${my_cmd}
    fi
}

set_localization
main "$@"
unset_localization
