#!/bin/bash

######## Script Information. BGN ########
# Author: liubingzhao.
# Date: 2016-12-23
######## Script Information. END ########

# All the global variables in this script.
function init_global_variables() {
    PRE_TEXTDOMAINDIR=$TEXTDOMAINDIR
    PRE_TEXTDOMAIN=$TEXTDOMAIN
    MK_DIR=`pwd`
}

function print_help() {
    cat << Help
$(gettxt "m | Binzo's customized TmakeGionee command.")
$(gettxt 'Usage:') m [PACKAGE]
Help
}

# Parse and validate the arguments.
# return 0: ok
# return 1: invalid or print help.
function parse_and_check_args () {
    while [ $# -gt 0 ];do
        case "$1" in
        -h|--help|\?)
            print_help
            return 1    # exit.
            ;;
        *)
            shift
            ;;
        esac
    done
}

# Internationalization and localization
# Set local language support. only for zh_CN.
# Reference directory: /usr/local/share/locale
function set_localization() {
    export TEXTDOMAINDIR="${MYSHELLDIR}/lang/locale"
    export TEXTDOMAIN="m"
}

function unset_localization() {
    if [ -z "$PRE_TEXTDOMAINDIR" ]; then
        unset TEXTDOMAINDIR
    fi
    if [ -z "$PRE_TEXTDOMAIN" ]; then
        unset TEXTDOMAIN
    fi
}

function check_mk_dir() {
    local mypwd=`pwd`
    local dst_file=
    while [ -n "${mypwd}" ]; do
        dst_file=${mypwd}/Android.mk
        if [ -f "${dst_file}" ]; then
            MK_DIR=${mypwd}
            break;
        else
            mypwd=${mypwd%\/*}
        fi
    done
}

# $1 由当前目录向上遍历每一级目录，查找文件 export.sh
function source_export() {
    local dst_file=export.sh
    local mypwd=`pwd`
    while [ -n "${mypwd}" ]; do
        if [ -f "${mypwd}/${dst_file}" ]; then
            cat ${mypwd}/${dst_file}
            read -p "source ${mypwd}/${dst_file}? (y/n)" ANSWER
            if [[ ${ANSWER} == y || ${ANSWER} == Y ]]; then
                source ${mypwd}/${dst_file}
            fi
            break;
        else
            mypwd=${mypwd%\/*}
        fi
    done
}

function main() {
    init_global_variables

    # Check arguments.
    parse_and_check_args "$@"
    case "$?" in
    1)
        return 1
        ;;
    *)
        ;;
    esac

    if [ -z "${MY_GN_PROD}" ]; then
        source_export
    fi
    if [ ! -f Android.mk ]; then
        check_mk_dir
    fi
    local my_cmd=
    if [ -f ${MK_DIR}/Android.mk ]; then
        # If Android.mk exists in current directory
        cd_dir TmakeGionee
        local root_dir=`pwd`
        MK_DIR=${MK_DIR#*${root_dir}/}
        # 在这里当前路径指定为android目录，方便复制编译结果(adb push out/xxx/.jar)。
        my_cmd="./TmakeGionee -t ${MY_GN_PROD} -p ${MK_DIR}"
        local log_file=/tmp/mk.log
        ${my_cmd} | tee ${log_file}
        echo --------
        grep "Install: " ${log_file}
    elif [ -f TmakeGionee ]; then
        # If currently in the android project root directory.
        if [ -z "$1" ]; then
            my_cmd="./TmakeGionee -t ${MY_GN_PROD} -n"
        elif [ ! -d $1 ]; then
            echo "No such directory."
            return 1
        elif [ -f $1/Android.mk ]; then
            my_cmd="./TmakeGionee -t ${MY_GN_PROD} -p $1"
        fi
        if [ -n "${my_cmd}" ]; then
            echoW ${my_cmd}
            read -p "Execute this command(y/n)?" ANSWER
            if [[ ${ANSWER} == y || ${ANSWER} == Y ]]; then
                ${my_cmd}
            fi
        fi
    fi
}

set_localization
main "$@"
unset_localization
