#!/bin/bash

######## Script Information. BGN ########
# Author: liubingzhao.
# Date: 2016-01-12
######## Script Information. END ########

# All the global variables in this script.
function init_global_variables() {
    target_line=
    idVendor=
    idProduct=
    TARGET=/etc/udev/rules.d/51-android.rules
    CONTENT=
}

function print_help() {
    cat << Help
$(gettxt "add-phone | Binzo's command to add usb access permission to file") $TARGET
$(gettxt "If we don't have permission to access usb device, add-phone can help us to finish the configuration.")
Help
}

# Parse and validate the arguments.
# return 0: ok
# return 1: print help.
function parse_and_check_args ()
{
    while [ $# -gt 0 ];do
        case "$1" in
            -h|--help|\?)
                print_help
                return 1    # exit.
                ;;
            *)
                shift
                ;;
        esac
    done
}

# use 'diff' command to gather usb device infomation.
function gather_info() {
    local lsusb_pluged=/tmp/lsusb_pluged
    local lsusb_unpluged=/tmp/lsusb_unpluged
    local lsusb_diff=/tmp/lsusb_diff

    read -p "$(gettxt 'Please unplug the usb cable, and then press any key...')"
    lsusb > $lsusb_unpluged
    read -p "$(gettxt 'Please replug the usb cable, and then press any key...')"
    lsusb > $lsusb_pluged
    diff $lsusb_pluged $lsusb_unpluged > $lsusb_diff
    while read line; do
        if [[ $line == \<* ]]; then
            target_line=$line
            echo diff line: $line
        fi
    done < $lsusb_diff
}

function cut_string() {
    target_line=${target_line#* ID }
    target_line=${target_line:0:9}
    idVendor=`echo $target_line|awk -F ":" '{print $1}'`
    idProduct=`echo $target_line|awk -F ":" '{print $2}'`
}

# Internationalization and localization
# Set local language support. only for zh_CN.
# Reference directory: /usr/local/share/locale
function set_localization() {
    export TEXTDOMAINDIR="${MYSHELLDIR}/lang/locale"
    export TEXTDOMAIN="add-phone"
}

function unset_localization() {
    unset TEXTDOMAINDIR
    unset TEXTDOMAIN
}

function main() {
    init_global_variables
    set_localization

    parse_and_check_args "$@"
    chk_return

    gather_info
    if [ -z "${target_line}" ]; then
        echoE $(gettxt "Not gathered this usb device information.")
        return 0
    fi
    cut_string
    CONTENT="SUBSYSTEM==\"usb\", ATTR{idVendor}==\"${idVendor}\", ATTR{idProduct}==\"${idProduct}\", MODE=\"0600\", OWNER=\"${USER}\""
    if [ -n "$(grep ${idVendor} ${TARGET}|grep ${idProduct}|grep ${USER})" ]; then
        echo $(gettxt "Do not need to config, you already have the permission to access device") "${idVendor}:${idProduct}"
        echo $(gettxt "If you still can not access the device, replug usb cable and try again.")
        return 0
    fi
    echoW $(gettxt "Please select and copy the content below, and then press any key to open '51-android.rules' file to paste or edit manually.")
    echoI $CONTENT
    read
    sudo vim $TARGET
    echoW $(gettext -s "You have to replug the usb cable again.")
    unset_localization
}

main "$@"
