#!/bin/bash

help()
{
    echoI "Help: Add device to file /etc/udev/rules.d/51-android.rules"
}

function choose_device() {
    # 执行lsusb命令，将结果存入临时文件
    tmp=/tmp/lsusb
    lsusb > $tmp
    # 按行遍历文件内容，行号一并输出
    let i=1
    while read line; do
        echo $i : $line
        let i=i+1
    done < $tmp
    let i=i-1
    # 让用户选择设备，即行号。
    read -p "Please choose usb device [1,$i] :" ANSWER
    while [ $ANSWER -gt $i -o $ANSWER -lt 1 ]; do
        read -p "Invalid. Choose again [1,$i] :" ANSWER
    done
    # 想办法执行 sed -n 3p file 命令
    arg_line=$ANSWER'p'
    cmd="sed -n $arg_line $tmp"
    CHOSEN=`$cmd`
}

function cut_string() {
    CHOSEN=${CHOSEN#* ID }
    CHOSEN=${CHOSEN:0:9}
    idVendor=`echo $CHOSEN|awk -F ":" '{print $1}'`
    idProduct=`echo $CHOSEN|awk -F ":" '{print $2}'`
}


CHOSEN=
idVendor=
idProduct=
choose_device
cut_string
echo idVendor=$idVendor; idProduct=$idProduct; OWNER=$USER


TARGET=/etc/udev/rules.d/51-android.rules
echoW "请复制如下内容到剪贴板，然后按任意键即可打开51-android.rules文件进行粘贴操作或者手动编辑。"
echoW "Please select and copy the content below, and then press any key to open '51-android.rules' file to paste or edit manually."
CONTENT="SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$idVendor\", ATTR{idProduct}==\"$idProduct\", MODE=\"0600\", OWNER=\"$USER\""
echo $CONTENT
read
sudo vim $TARGET
echoW "重新插拔设备使其生效。"
echoW "Replug the usb device again."
