#!/bin/bash

######## Script Information. BGN ########
# Author: liubingzhao.
# Date: 2015-12-08
######## Script Information. END ########

function print_help() {
    echoI "Help: c | Binzo's customized 'cd'"
    cat << Help
usage: c [-h|--help|?] [KEYWORD]
    缺省参数   返回上级目录，相当于命令"cd .."
    [KEYWORD]  返回到路径中指定关键字开头的目录
Help
    return $?
}

# $1 : 寻找绝对路径中以$1开头的目录
function find_dir() {
    if [ -n "${MYPROJECTDIR}" ]; then
        local proj="${MYPROJECTDIR}/$1"
        if [ -d "${proj}" ]; then
            cd ${proj}/L*/a*
            if [ -f ${proj}/export.sh ]; then
                source ${proj}/export.sh
            fi
            return $?
        fi
    fi
    local dir_name
    local target_dir=
    local mypwd="$(dirname "$(pwd)")"
    while [[ ${mypwd} != / ]]; do
        dir_name=$(basename "${mypwd}")
        if [[ ${dir_name} == ${1}* ]]; then
            target_dir="${mypwd}"
            break
        fi
        mypwd=$(dirname "${mypwd}")
    done
    if [ -n "${target_dir}" ]; then
        cd "${target_dir}"
        return $?
    fi
}

function main() {

    # 判断参数个数
    if [ $# -eq 0 ]; then
        cd ..
        return $?
    elif [ $# -gt 1 ]; then
        echoE "只可指定一个参数"
        return 1
    fi
    while [ $# -gt 0 ];do
        case "$1" in
            -h|--help|\?)
                print_help
                return $?
                ;;
            -)
                cd -
                return $?
                ;;
            *)
                if [ -d "$1" ]; then
                    # 有效文件夹路径
                    cd "$1"
                    return $?
                elif [ -f "$1" ]; then
                    # 有效文件路径，直接进入文件所在的目录
                    cd $(dirname $1)
                    return $?
                else
                    find_dir "$1"
                    return $?
                fi
                shift
                ;;
        esac
    done

}

main "$@"
