#!/bin/bash

######## Script Information. BGN ########
# Author: liubingzhao.
# Date: 2016-12-27
# Relative Command: commands/grep
######## Script Information. END ########

print_help()
{
    echoI "Help: c | Binzo's customized 'cd'"
    cat << Help
usage: c [NUM] [-h|--help] [p] [r] [DIRECTORY]
    缺省参数   Return to the parent directory.
              返回上级目录，相当于命令"cd .."。
    [NUM]     返回上级n个目录。如"c 3"相当于"cd ../../.."
    [p]       Enter my (P)roject directory. 
              进入我的项目主目录，相当于"cd ~/Projects"
    [r]       Enter (R)oot path of current project.
              如果当前处在某个项目目录的子目录下，返回到项目根目录.
              判断条件为"TmakeGionee"所在目录
    [DIRECTORY]  Enter a specific directory. 
                 cd到一个指定的目录.
Help
}

cd_repo_dir()
{
    mypwd=`pwd`
    while [ -n "${mypwd}" ]; do
        if [ -d "${mypwd}/.repo" ]; then
            break;
        else
            mypwd=${mypwd%\/*}
        fi
    done
    if [ -n "${mypwd}" ]; then
        cd ${mypwd}
    else
        # 没有发现.repo目录，恢复到原来位置
        echoW "路径中没有找到.repo目录！"
    fi
}

# $1 寻找目录下存在$1的文件或目录
function cd_dir()
{
    mypwd=`pwd`
    while [ -n "${mypwd}" ]; do
        if [ -d "${mypwd}/$1" -o -f "${mypwd}/$1" ]; then
            break;
        else
            mypwd=${mypwd%\/*}
        fi
    done
    if [ -n "${mypwd}" ]; then
        cd "${mypwd}"
    else
        # 没有发现目标目录，恢复到原来位置
        echoW "路径中没有找到$1目录！"
    fi
}

function check_integer() {
    var=$(echo $1 | bc 2>/dev/null)
    if [ ${var} = $1 ]; then
        return 1
    else
        return 0
    fi
}

function setproject() {
    if [ -n "$1" ]; then
        if [ -d $1 ]; then
            if [[ $1 == /* ]]; then
                MY_PROJECT=$1
            else
                MY_PROJECT=`pwd`/$1
            fi
        else
            echoE "目录不存在"
        fi
        echoI MY_PROJECT=$MY_PROJECT
    else
        echoE "未指定project参数"
    fi
}

function getproject() {
    echo $MY_PROJECT
}

if [ -z $1 ]; then # 缺省参数
    cd ..
elif [ -d $1 ]; then # 有效路径
    cd $1
elif [ "$1" = "--help" -o "$1" = "-h" ]; then
    print_help
elif [ "$1" = "p" ]; then
    if [ -z "$MY_PROJECT" ]; then
        cd ~/Projects
    else
        cd $MY_PROJECT
    fi
elif [ "$1" = "r" ]; then
    #cd_repo_dir
    cd_dir TmakeGionee
elif [ "$1" = "-" ]; then
    # 返回上一次访问过的目录
    cd -
else
    check_integer $1
    arg_is_int=$?
    # 参数为数字，返回N级目录
    if [[ $arg_is_int == 1 ]]; then
        mypwd=`pwd`
        let num=$1
        while [ ${num} -gt 0 ]; do
            mypwd=${mypwd%\/*}
            let num=`expr ${num} - 1`
        done
        cd "${mypwd}"
    else
        echoE "c $1: 没有此目录！"
    fi
fi
