#!/bin/bash

# All the global variables in this script.
function init_global_variables() {
    MY_EXCEPTS="external out release cts sdk ndk dalvik docs pdk"
}

function print_help() {
    echoI "Help: f | Binzo's customized 'find'"
    cat << Help
Usage:
    f <KEYWORD> 仅限一个参数
                在当前目录下搜索所有文件中指定的关键字。
    f . [OPTIONS]
                多个参数直接调用find原始命令并执行

Help
}


# Parse and validate the arguments.
# return 0: ok
# return 1: invalid or print help.
function parse_and_check_args () {
    args="$@"
    flag=
    for arg in $args; do
        if [ "$arg" = "-h" -o "$arg" = "--help" ]; then
            help
            # 打印帮助信息直接返回
            return 0
        fi
    done

    if [ -z "$1" ]; then
        echoE "没有参数！"
    # 只有一个参数
    elif [ -n "$1" -a -z "$2" ]; then
        find . -iname $1
    else
        find $*
    fi

    return 1
}

function main() {
    parse_and_check_args "$@"

}

main "$@"
