#!/bin/bash

MY_EXCEPTS="external out release cts sdk ndk dalvik docs pdk"

help()
{
    echoI "Help: f | Binzo's customized 'find'"
    cat << Help
Usage:
    f <KEYWORD> 仅限一个参数
                在当前目录下搜索所有文件中指定的关键字。
    f . [OPTIONS]
                多个参数直接调用find原始命令并执行

Help
}

# 解析参数并且进行有效性验证
# return    返回是否解析成功，若有非法参数返回0，OK返回1
function parse_and_check_args ()
{
    args="$*"
    flag=
    for arg in $args; do
        if [ "$arg" = "-h" -o "$arg" = "--help" ]; then
            help
            # 打印帮助信息直接返回
            return 0
        fi
    done

    if [ -z "$1" ]; then
        echoE "没有参数！"
    # 只有一个参数
    elif [ -n "$1" -a -z "$2" ]; then
        find . -iname $1
    else
        find $*
    fi

    return 1
}

parse_and_check_args $*

