#!/bin/bash

print_help()
{
    echoI "Help: n | Binzo's customized 'nautilus'"
    cat << Help
usage: n [-h|--help] [99|100] [DIRECTORY]
    缺省参数  打开可视化窗口
    [99|100]  打开ftp://10.10.100.99 | ftp://10.10.100.100
              以可视化窗口访问ftp服务器
    [DIRECTORY]  以可视化窗口打开指定目录
Help
}


if [ -z $1 ]; then # 缺省参数
    nautilus
elif [ -d $1 ]; then # 有效路径
    nautilus $1
elif [ "$1" = "--help" -o "$1" = "-h" ]; then
    print_help
elif [[ $1 == ftp* ]]; then
    nautilus "$1"
else
    echoE "n $1: 没有此目录！"
fi
