#!/bin/bash

# 不限参数，判断参数个数
function sizeof() {
    echo $#
}

# 判断软件包是否已安装
function pkgInstalled() {
    if [ -n "$1" ]; then
        dpkg -l | grep "$1"
        search=`dpkg -l | grep "$1"`
        if [ -n "$search" ]; then
            found=true
            echoI "'$1'已安装"
            return 1
        else
            echo "'$1'未安装"
            return 0
        fi
    else
        echoE "缺少参数，请指定PackageName"
    fi
}

# Return 0: valid.
# Return 1: invalid.
function chkInt() {
    case "$1" in
    [0-9]*)
        #echo "$1 is a positive integer."
        return 0
        ;;
    *)
        #echoE "$1 is not a positive integer."
        return 1
        ;;
    esac
}
