#!/bin/bash

# 不限参数，判断参数个数
function sizeof() {
    echo $#
}

# 判断软件包是否已安装
function pkgInstalled() {
    if [ -n "$1" ]; then
        dpkg -l | grep "$1"
        search=`dpkg -l | grep "$1"`
        if [ -n "$search" ]; then
            found=true
            echoI "'$1'已安装"
            return 1
        else
            echo "'$1'未安装"
            return 0
        fi
    else
        echoE "缺少参数，请指定PackageName"
    fi
}

# Return 0: valid.
# Return 1: invalid.
function chkInt() {
    case "$1" in
    [0-9]*)
        #echo "$1 is a positive integer."
        return 0
        ;;
    *)
        #echoE "$1 is not a positive integer."
        return 1
        ;;
    esac
}

# $1 寻找目录下存在$1的目录并执行cd命令
function cd_dir()
{
    mypwd=`pwd`
    while [ -n "${mypwd}" ]; do
        if [ -d "${mypwd}/$1" -o -f "${mypwd}/$1" ]; then
            break;
        else
            mypwd=${mypwd%\/*}
        fi
    done
    if [ -n "${mypwd}" ]; then
        cd "${mypwd}"
    else
        echoW "路径中没有找到$1目录！"
    fi
}
