#!/bin/bash

# coded by liubzh

# ftp server infomation
host="10.10.100.100"
user="read"
pass="123456"


# 1st step
get_folder_list ()
{

ftp -n<<! 
open $host
user $user $pass
cd $FOR_NAME
prompt # set prompt off
ls . $REMOTE_FOLDER_LIST_TEMP
close
bye
!

}


# 2nd step
choose_folder ()
{
    folders=
    while read line; do
        # cut the content to find out folder name.
        folder="${line##* }"
        folders+="$folder "
    done < $REMOTE_FOLDER_LIST_TEMP
    read -p "Get latest folder [$folder]? ([Enter]/Y/y/...)" -t 10 ANSWER
    if [ "$ANSWER" = "Y" -o "$ANSWER" = "y" -o "$ANSWER" = "" ]; then
        REMOTE_FOLDER="$folder"
    else
        select folder in $folders; do
            REMOTE_FOLDER=$folder
            break;
        done
    fi
}


# 3rd step
get_file_path ()
{

ftp -n<<! 
open $host
user $user $pass
binary # binary file.
prompt # set prompt on
nlist $FOR_NAME/$REMOTE_FOLDER $REMOTE_FILE_PATH_TEMP
close
bye
!

REMOTE_FILE_PATH=`cat $REMOTE_FILE_PATH_TEMP`

}


# 4th step
download_file ()
{

# $1: the remote file path.
# $2: the local target directory path.
ftp -n<<! 
open $host
user $user $pass
binary # binary file.
get $REMOTE_FILE_PATH $TARGET_PATH/${REMOTE_FILE_PATH##*/}
close
bye
!

}

# 5th step
adb_push() {
    if [[ $REMOTE_FOLDER == *\$* ]]; then
        read -p "adb push ? ([Enter]/Y/y/...)" -t 10 ANSWER
        if [ "$ANSWER" = "Y" -o "$ANSWER" = "y" -o "$ANSWER" = "" ]; then
            PUSH_FILE=${REMOTE_FOLDER#*_$}
            PUSH_FILE=${PUSH_FILE//\$/\/}
            adb remount
            adb push $TARGET_PATH/$(basename $PUSH_FILE) $PUSH_FILE
        fi
    fi
}

REMOTE_FOLDER=
REMOTE_FILE_PATH=
TARGET_PATH="$HOME/get"
if [ ! -d $TARGET_PATH ]; then
    mkdir $TARGET_PATH
fi
REMOTE_FOLDER_LIST_TEMP="$TARGET_PATH/.list"
REMOTE_FILE_PATH_TEMP="$TARGET_PATH/.file"

# for specific username folder, the default is 'liubzh'
FOR_NAME="liubzh"
if [ -n "$1" ]; then
    FOR_NAME="$1"
    echo "For --> $FOR_NAME"
fi
echo "Default: --> '$FOR_NAME'"

get_folder_list
choose_folder
get_file_path
download_file
adb_push
